---

- block:
  - name: '{{ outer_item.split(".yml")[0] | basename }} | command | findmnt | FSTYPE | ce778a20'
    command:
      cmd: 'findmnt --noheadings --output FSTYPE --target /boot'
    changed_when: false
    register: register_ce778a20

  - name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.set_fact | partition_boot_fstype | d8b3ea5e'
    ansible.builtin.set_fact:
      partition_boot_fstype: "{{ register_ce778a20.stdout | default('NULL') }}"

  - name: '{{ outer_item.split(".yml")[0] | basename }} | command | findmnt | SOURCE | f47c97ce'
    command:
      cmd: 'findmnt --noheadings --output SOURCE --target /boot'
    changed_when: false
    register: register_f47c97ce

  - name: '{{ outer_item.split(".yml")[0] | basename }} | command | e2label | b1a2cdd0'
    command:
      cmd: 'e2label {{ register_f47c97ce.stdout }} boot'
    when: partition_boot_fstype is match('^ext3|ext4$')

  - name: '{{ outer_item.split(".yml")[0] | basename }} | command | xfs_io | ba297212'
    command:
      cmd: 'xfs_io -c "label -s boot" /boot'
    when: partition_boot_fstype is match('^xfs$')

  - name: '{{ outer_item.split(".yml")[0] | basename }} | command | findmnt | LABEL | b4fed566'
    command:
      cmd: 'findmnt --noheadings --output LABEL --target /boot'
    changed_when: false
    register: register_b4fed566

  - name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.fail | Conditional | Failed boot labeling | 7ada9309'
    ansible.builtin.fail:
      msg: 'FAIL :: Could not validate proper labeling of /boot :: 7ada9309'
    when: not register_b4fed566.stdout is match('^boot$')

  - name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.copy | {{ playbook_task_run_file }} | Write task run state | 115f23fb'
    ansible.builtin.copy:
      dest: '{{ playbook_task_run_file }}'
      owner: 'root'
      group: 'root'
      mode: 0600
      content: '0040'
    changed_when: false

  when: playbook_task_run | int < 0040
