---

- name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.stat | /sys/firmware/efi | 1d9a2ffe'
  ansible.builtin.stat:
    path: '/sys/firmware/efi'
  register: register_1e87b6df

- name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.set_fact | node_hardware_type | a3763ac9'
  ansible.builtin.set_fact:
    node_hardware_type: 'BIOS'
  when: not register_1e87b6df.stat.exists

- name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.set_fact | node_hardware_type | 22265cbd'
  ansible.builtin.set_fact:
    node_hardware_type: 'EFI'
  when: register_1e87b6df.stat.isdir is defined and register_1e87b6df.stat.isdir

- name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.fail | Conditional | Node hardware type incorrectly set | d0d7c351'
  ansible.builtin.fail:
    msg: "FAIL :: Could not determine node hardware type :: Fact 'node_hardware_type' is undefined :: d0d7c351"
  when: node_hardware_type is undefined
