---

- block:
  - name: '{{ outer_item.split(".yml")[0] | basename }} | command | chroot | /mnt/default | dracut | regenerate | c4733251'
    command:
      cmd: 'chroot /mnt/default /bin/dracut --force --regenerate-all'

  - name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.copy | {{ playbook_task_run_file }} | Write task run state | 6ee5b2d5'
    ansible.builtin.copy:
      content: '0120'
      dest: '{{ playbook_task_run_file }}'
      group: 'root'
      mode: 0600
      owner: 'root'
    changed_when: false

  when: playbook_task_run | int < 0120
