---

- block:
  - name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.posix.mount | Unmount filesystems | 19a7d1d4'
    ansible.posix.mount:
      path: '{{ item }}'
      state: 'unmounted'
    with_items:
      - /mnt/default/sys
      - /mnt/default/proc
      - /mnt/default/dev
      - /mnt/default/boot
      - /mnt/default/var
      - /mnt/default/tmp
      - /mnt/default/home
      - /mnt/default

  - name: '{{ outer_item.split(".yml")[0] | basename }} | community.general.lvol | Deactivate logical volumes | 1aec1f25'
    community.general.lvol:
      active: false
      lv: '{{ item }}'
      vg: 'default'
    with_items:
      - swap
      - var
      - tmp
      - root
      - home

  - name: '{{ outer_item.split(".yml")[0] | basename }} | community.crypto.luks_device | Close container | default | 4b6dc819'
    community.crypto.luks_device:
      name: 'default'
      state: 'closed'

  - name: '{{ outer_item.split(".yml")[0] | basename }} | ansible.builtin.copy | {{ playbook_task_run_file }} | Write task run state | df239197'
    ansible.builtin.copy:
      content: '0170'
      dest: '{{ playbook_task_run_file }}'
      group: 'root'
      mode: 0600
      owner: 'root'
    changed_when: false

  when: playbook_task_run | int < 0170
